backend:
  name: github
  repo: abubakralmansouri32-coder/jishan-news
  branch: main

media_folder: "content/news/images"
public_folder: "/content/news/images"

collections:
    - name: "news"
    label: "الأخبار"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
            - label: "العنوان"
        name: "title"
        widget: "string"
            - label: "القسم"
        name: "category"
        widget: "select"
        options:
                    - "سياسة"
                    - "محليات"
                    - "رياضة"
                    - "اقتصاد"
                    - "مقالات"
            - label: "المحتوى"
        name: "body"
        widget: "markdown"
